# Use the official Node.js image as the base image
FROM node:14-alpine

WORKDIR /backend

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 5000

CMD ["node", "server.js"]
# hi