# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Install MongoDB client tools
RUN apt-get update && apt-get install -y mongodb-clients

# Set the working directory in the container
WORKDIR /usr/src/data

# Copy the JSON files into the container
COPY shopify_db.products.json .
COPY shopify_db.users.json .

# Expose MongoDB default port
EXPOSE 27017

# Run MongoDB import commands during container startup
CMD mongoimport --host mongodb --db shopify_db --collection products --file shopify_db.products.json --jsonArray && \
    mongoimport --host mongodb --db shopify_db --collection users --file shopify_db.users.json --jsonArray

# docker network create shopify-network
# docker run -d --name mongodb --network shopify-network -p 27017:27017 my-mongodb-image
# docker run -d --name shopify-back -p 5000:5000 shopify-back